🔧 (deploy.yml): update SSH key handling to use $SSH_PRIVATE_KEY environment variable for better security and error handling 🔧 (deploy.yml): change scp command to remove verbose flag for cleaner output 🔧 (pytest.yml): update job name to start redis container for clarity and consistency with other job names

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -65,13 +65,14 @@ jobs:
           sudo apt-get install -y openssh-client
 
           eval "$(ssh-agent -s)"
-          echo "${{ secrets.SERVER_SSH_KEY }}" | tr -d '\r' | ssh-add -
+
+          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - || { echo "Failed to add SSH key to agent"; exit 1; }
 
           mkdir -p ~/.ssh
           touch ~/.ssh/known_hosts
           ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts
 
-          scp -v .env $EC2_USER@$EC2_HOST:~/arctic-fox/
+          scp .env $EC2_USER@$EC2_HOST:~/arctic-fox/
 
           ssh -v -tt $EC2_USER@$EC2_HOST << EOF
             set -e
